#!/bin/sh

duplicates=$(grep -h color plugins/*/info.json | cut -d: -f2 | sed -r 's/.*"(.*)".*/\1/' | sort | uniq -d)

if [ -n "$duplicates"  ]
then
  echo "There are multiple comics with the same color:"
  echo "$duplicates"
  exit 1
fi

exit 0
